# Generated by Django 3.2.9 on 2021-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0002_delete_ishchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='talabalar',
            name='biladigan_dasturlash_tili',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talabalar',
            name='yoshi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='qachon_oqigan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
